

x-common-configs: &common-configs
  env_file: .env.runtime
  deploy:
    resources:
      limits:
        cpus: 1
        memory: "2048M"
  depends_on:
    - tfb-database


services:
  nginx:
    image: nginx

  bench:
    build:
      dockerfile: Dockerfile
      context: bench
      #platforms: [linux/amd64/v8]

    volumes:
      - "./bench/:/app"

  rails-mri:
    << : *common-configs
    build:
      dockerfile: rails.dockerfile
      context: rails


  rails-truffle:
    << : *common-configs
    build:
      dockerfile: rails-truffle.dockerfile
      context: rails

  rails-truffle-graalvm:
    << : *common-configs
    build:
      dockerfile: rails-truffle-graalvm.dockerfile
      context: rails
      platforms: [linux/amd64]

  tfb-database:
    build:
      dockerfile: postgres.dockerfile
      context: postgres
