

x-common-configs: &common-configs
  environment:
    - RAILS_MAX_THREADS=1
  deploy:
    resources:
      limits:
        cpus: 1
        memory: "2048M"
  depends_on:
    - tfb-database

services:
  nginx:
    image: nginx
    ports:
      - 8080:80

  bench:
    build:
      dockerfile: Dockerfile
      context: bench
      platforms: [linux/amd64]

  rails-mri:
    << : *common-configs
    build:
      dockerfile: rails.dockerfile
      context: rails
      platforms: [linux/amd64]


  rails-truffle:
    << : *common-configs
    build:
      dockerfile: rails-truffle.dockerfile
      context: rails
      platforms: [linux/amd64]

  rails-truffle-graalvm:
    << : *common-configs
    build:
      dockerfile: rails-truffle-graalvm.dockerfile
      context: rails
      platforms: [linux/amd64]

  tfb-database:
    build:
      dockerfile: postgres.dockerfile
      context: postgres
