services:
  rails-mri:
    build:
      dockerfile: rails.dockerfile
      context: rails

    ports:
      - 8080:8080

  tfb-database:
    build:
      dockerfile: postgres.dockerfile
      context: postgres
