services:
  postgres:
    image: postgres:17.4-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
